config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, only: [:index]
  resources :products, only: [:index]
  resources :purchases, only: [:index]
  get '/cart', to: 'purchase_items#index'
  resources :purchase_items, path: '/cart/items'

  get '/cart/checkout', to: 'purchases#new', as: :checkout
  patch '/cart/checkout', to: 'purchases#create'

  namespace :admin do
    root 'admin_panel#index'
    resources :admin_panel
    resources :users
    resources :categories
    get '/statistics', to: 'statistics#index'
    resources :products do
      collection { post :import }
    end
    resources :purchases
  end

  namespace :api do
    root 'products#index'
    resources :products
  end

  root to: 'home#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ShopApp</a>
  <% if user_signed_in? %>
    <%= link_to pluralize(current_cart.items_count, 'item'), cart_path, class: 'nav-link' %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if @current_user&.admin? %>
      <li class="nav-item">
        <%= link_to 'Admin panel', admin_admin_panel_index_path, class: "nav-link" %>
      </li>
    <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to @current_user.email, edit_user_registration_path, method: :get, class: 'navbar-brand' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Purchases', purchases_path, method: :get, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :get, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>