config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, only: [:index]
  resources :products, only: [:index]
  resources :purchases, only: [:index]
  get '/cart', to: 'purchase_items#index'
  resources :purchase_items, path: '/cart/items'

  get '/cart/checkout', to: 'purchases#new', as: :checkout
  patch '/cart/checkout', to: 'purchases#create'

  namespace :admin do
    root 'admin_panel#index'
    resources :admin_panel
    resources :users
    resources :categories
    get '/statistics', to: 'statistics#index'
    resources :products do
      collection { post :import }
    end
    resources :purchases
  end

  namespace :api do
    root 'products#index'
    resources :products
  end

  root to: 'home#index'
end

app/models/statistic.rb
class Statistic

  def purchases_count
    @purchases_searched do |purchase|
    purchase.
  end
  end

end

app/controllers/admin/statistics_controller.rb
module Admin
  class StatisticsController < ApplicationController

    def index
      @q = Purchase.all.where(status: :open)
                   .order(updated_at: :desc)
                   .ransack(params[:q])
      @q_items = PurchaseItem.all.ransack(params[:q])
      @q_users = User.all.ransack(params[:q])
      @purchases_searched = @q.result(distinct: true).paginate(page: params[:page], per_page: 5)
      @items_searched = @q_items.result(distinct: true)
    end
  end
end

app/views/admin/statistics/_search_form.html.erb
<%= search_form_for @q, url: admin_statistics_path do |f| %>
  <%= f.label "Take range from:" %><br>
  <%= f.date_select :updated_at_gteq %><br>
  <%= f.label "To:" %><br>
  <%= f.date_select :updated_at_lteq %><br>
  <br>
  <%= f.submit "Search", class: "btn btn-primary" %>
<% end %>
<%= link_to "Clear Search", admin_statistics_path, class: "cancel-button" %>
<br>
<br>

app/views/admin/statistics/index.html.erb
<h2>Statistics</h2>

<%= render 'admin/statistics/search_form' %>

<%= link_to 'Back', admin_admin_panel_index_path, class: "btn btn-secondary" %>
<br>
<br>
<strong>Total orders: </strong><%= @purchases_searched.count %>
<br>
<strong>Orders value: </strong><%= number_to_currency(@purchases_searched.sum(&:sub_total)) %>
<br>
<strong>Total items ordered: </strong><%= @items_searched.sum(&:quantity) %>
<br>
<strong>Ordering Users: </strong><%= @purchases_searched.map(&:user_id).uniq.count %>
<br>
<strong>Most ordered items: </strong><%= @items_searched.map(&:product_id).uniq.count %>
<br>
<br>
<% @items_searched.map(&:product_id).uniq.each do |item_uniq| %>
  <li>
      <strong>- </strong><%= Product.find(item_uniq).name %>
  </li>
<% end %>
<br>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @purchases_searched %>
  </div>
  <%= will_paginate @purchases_searched, :container => false %>
</div>
<% @purchases_searched.each do |purchase| %>
  <table class="table  table-stripes table-bordered table-hover">
    <tr style="background-color: #D6EEEE">
      <td><strong>User email: </strong><%= purchase.user.email %></td>
      <td><strong>Purchase token: </strong><%= purchase.token %></td>
      <td><strong>Updated at: </strong><%= purchase.updated_at %></td>
      <td><strong>Order value: </strong><%= number_to_currency(purchase.sub_total) %></td>
    </tr>
    <tr>
      <td colspan="4"><strong>Ordered items:</strong></td>
    </tr>
    <% purchase.items.each do |purchase_item| %>
      <tr>
        <td colspan="2"><strong>Name: </strong><%= purchase_item.product.name %></td>
        <td><strong>Quantity: </strong><%= purchase_item.quantity %></td>
        <td><strong>Items price: </strong><%= number_to_currency(purchase_item.price) %></td>
      </tr>
    <% end %>
    <br>
<% end %>