config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, only: [:index]
  resources :products, only: [:index]
  resources :purchases, only: [:index]
  get '/cart', to: 'purchase_items#index'
  resources :purchase_items, path: '/cart/items'

  get '/cart/checkout', to: 'purchases#new', as: :checkout
  patch '/cart/checkout', to: 'purchases#create'

  namespace :admin do
    root 'admin_panel#index'
    resources :admin_panel
    resources :users
    resources :categories
    get '/statistics', to: 'statistics#index'
    resources :products do
      collection { post :import }
    end
    resources :purchases
  end

  namespace :api do
    root 'products#index'
    resources :products
  end

  root to: 'home#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_products
  has_many :products, through: :category_products
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < BaseController
    before_action :set_category, only: %i[ show edit update destroy ]

    def index
      @q = Category.all.order(name: :asc).ransack(params[:q])
      @categories_searched = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
      @category = Category.new
    end

    def show
    end

    def edit
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to admin_categories_path, notice: "Category added"
      else

      end
    end

    def update
      @category.update(category_params)
      redirect_to admin_categories_path, notice: "Category updated"
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy
      redirect_to admin_categories_path, notice: "Category deleted"
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save
  end

  def update
    @category.update(category_params)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(
    :products,
    :name,
    :uid,
    :description,
    category_products_attributes: [:id, :product_id]
    )
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save
  end

  def update
    @category.update(category_params)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(
    :products,
    :name,
    :uid,
    :description,
    category_products_attributes: [:id, :product_id]
    )
  end
end

app/views/admin/categories/_form_fields.html.erb
<%= f.input_field :name, class: "form-control", placeholder: "Name" %>
<%= f.input_field :description, size: "70x5", class: "form-control", placeholder: "Description" %>

app/views/admin/categories/_search_form.html.erb
<%= search_form_for @q, url: admin_categories_path do |f| %>
  <%= f.label "Name contains:" %>
  <br>
  <%= f.search_field :name_cont %>
  <%= f.submit "Search", class:"btn btn-primary" %>
<% end %>
<%= link_to "Clear Search", admin_categories_path, class:"cancel-button" %>
<br>

app/views/admin/categories/edit.html.erb
<h2>Editing Category</h2>

<%= simple_form_for @category, as: :category, url: admin_category_path(@category) do |f| %>

  <%= render partial: 'form_fields', locals: { f: f } %>

  <%= f.button :submit, class: "btn btn-secondary" %>
  <%= link_to 'Back', admin_categories_path, class: "btn btn-secondary" %>
<% end %>

app/views/admin/categories/index.html.erb
<h2>Categories</h2>

<%= simple_form_for @category, as: :category, url: admin_categories_path do |f| %>

  <%= render partial: 'form_fields', locals: { f: f } %>
  <br>

  <%= f.button :submit, class: "btn btn-secondary" %>
  <%= link_to 'Back', admin_admin_panel_index_path, class: "btn btn-secondary" %>
<% end %>
<br>
<%= render 'admin/categories/search_form' %>
<br>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @categories_searched %>
  </div>
  <%= will_paginate @categories_searched, :container => false %>
</div>
<br>
<% @categories_searched.each do |category| %>
  <table class="table  table-stripes table-bordered table-hover">
    <tr style="background-color: #D6EEEE">
      <td>
        <strong>Name:</strong>
        <%= category.name %>
      </td>
      <td align="right">
        <%= link_to 'Edit', edit_admin_category_path(category), class: "btn btn-secondary" %>
        <%= link_to 'Delete', admin_category_path(category), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <strong>Description:</strong>
        <%= category.description %>
      </td>
    </tr>
<% end %>