config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, only: [:index]
  resources :products, only: [:index]
  resources :purchases, only: [:index]
  get '/cart', to: 'purchase_items#index'
  resources :purchase_items, path: '/cart/items'

  get '/cart/checkout', to: 'purchases#new', as: :checkout
  patch '/cart/checkout', to: 'purchases#create'

  namespace :admin do
    root 'admin_panel#index'
    resources :admin_panel
    resources :users
    resources :categories
    get '/statistics', to: 'statistics#index'
    resources :products do
      collection { post :import }
    end
    resources :purchases
  end

  namespace :api do
    root 'products#index'
    resources :products
  end

  root to: 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :category_products
  has_many :categories, through: :category_products
  has_one_attached :photo

  accepts_nested_attributes_for :category_products

  def self.to_csv(options = {})
    attributes = %w{ id name description archived on_stock created_at updated_at uuid price }
    CSV.generate(options.to_s, headers: true) do |csv|
      csv << attributes

      all.each do |product|
        csv << product.attributes.values_at(*attributes)
      end
    end
  end

  def self.import(file)
    attributes = %w{ id name description archived on_stock created_at updated_at uuid price }
    CSV.foreach(file.path, headers: true) do |row|
      product = find_by_id(row["{}id"]) || new
      product.attributes = row.to_hash.slice(*attributes)
      product.save!
    end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < BaseController
    before_action :set_product, only: %i[ show edit update destroy ]

    def index
      @q = Product.all.order(name: :asc).ransack(params[:q])
      @products_searched = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
      @product = Product.new
      @products = @q.result(distinct: true)

      respond_to do |format|
        format.html
        format.csv { send_data @products.to_csv, filename: "products_#{Date.today}.csv" }
        format.xls
      end
    end

    def import
      Product.import(params[:file])
      redirect_to admin_products_path, notice: "Products imported"
    end

    def show
    end

    def edit
    end

    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to admin_products_path, notice: "Product added"
      else

      end
    end

    def update
      @product.update(product_params)
      redirect_to admin_products_path, notice: "Product updated"
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to admin_products_path, notice: "Product deleted"
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(
        :categories,
        :name,
        :description,
        :price,
        :on_stock,
        :photo,
        :archived,
        category_ids: []
      )
    end
  end
end

app/controllers/api/products_controller.rb
module Api
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy ]

    def index
      @products = Product.all.order(name: :asc, id: :asc)
      render json: @products
    end

    def import
      Product.import(params[:file])
      redirect_to admin_products_path, notice: "Products imported"
    end

    def show
      render json: @product
    end

    def edit
    end

    def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to admin_products_path, notice: "Product added"
        render json: @product, status: :created, location: @product
      else
        render json: @product.errors, status: :unprocessable_entity
      end
    end

    def update
      @product.update(product_params)
      redirect_to admin_products_path, notice: "Product updated"
      render json: @product
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to admin_products_path, notice: "Product deleted"
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(
        :categories,
        :name,
        :description,
        :price,
        :on_stock,
        :photo,
        :archived,
        category_ids: []
      )
    end
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
  end

  def update
    @product.update(product_params)
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
  end

  def update
    @product.update(product_params)
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
      :categories,
      :name,
      :description,
      :price,
      :on_stock,
      :photo,
      :archived,
      category_ids: []
    )
  end
end

app/views/admin/products/_form_fields.html.erb
<%= f.text_field :name, class: "form-control", placeholder: "Name" %>
<%= f.text_area :description, size: "70x5", class: "form-control", placeholder: "Description" %>
<br>
<%= f.label "Price:" %>
<%= f.number_field :price, step: :any, class: "form-control" %>
<br>
<%= f.label "On stock:" %>
<%= f.number_field :on_stock, class: "form-control" %>
<%= f.file_field :photo, class: "form-control" %>


<% Category.all.each do |category| %>
  <%= check_box_tag "product[category_ids][]", category.id, f.object.categories.include?(category) %>
  <%= category.name %>
<% end %>
<br>
<br>

app/views/admin/products/_search_form.html.erb
<%= search_form_for @q, url: admin_products_path do |f| %>
  <%= f.label "Name contains:" %>
  <br>
  <%= f.search_field :name_cont %>
  <%= f.submit "Search", class:"btn btn-primary" %>
<% end %>
<%= link_to "Clear Search", admin_products_path, class:"cancel-button" %>
<br>
<br>

app/views/admin/products/edit.html.erb
<h2>Editing Product</h2>

<%= form_for @product, as: :product, url: admin_product_path(@product) do |f| %>

  <%= render partial: 'form_fields', locals: { f: f } %>

  <%= f.submit "Update Product", class: 'btn btn-secondary' %>
  <%= link_to 'Back', admin_products_path, class: "btn btn-secondary" %>
  <br>
  <%= f.check_box :archived, {}, true, false %>
  <%= f.label "Archived" %>
<% end %>

app/views/admin/products/index.html.erb
<h2>Products</h2>

<p>
  Export searched products to file:
  <%= link_to "CSV", admin_products_path(format: "csv") %>
  <%= link_to "XLS", admin_products_path(format: "xls") %>
</p>

Import products from CSV file:
<%= form_tag import_admin_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import", class: 'btn btn-secondary' %>
<% end %>

<%= form_for @product, as: :product, url: admin_products_path do |f| %>

  <%= render partial: 'form_fields', locals: { f: f } %>

  <%= f.submit "Create Product", class: 'btn btn-secondary' %>
  <%= link_to 'Back', admin_admin_panel_index_path, class: "btn btn-secondary" %>
<% end %>
<br>
<%= render 'admin/products/search_form' %>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @products_searched %>
  </div>
  <%= will_paginate @products_searched, :container => false %>
</div>
<br>
<% @products_searched.each do |product| %>
  <table class="table  table-stripes table-bordered table-hover">
    <tr>
      <td align="left" width="20%">
        <% if product.photo.attached? %>
          <%= image_tag product.photo, width: "200px" %>
          <br>
        <% else %>
          <strong>[Photo not available]</strong>
          <br>
        <% end %>
      </td>
      <td align="left" width="50%">
        <strong>Name:</strong>
        <%= product.name %>
        <br>
        <strong>Description:</strong>
        <%= product.description %>
        <br>
      </td>
      <td align="left" width="30%">
        <strong>Price:</strong>
        <%= number_to_currency(product.price) %>
        <br>
        <strong>on Stock:</strong>
        <%= product.on_stock %>
        <br>
        <strong>Categories:</strong>
        <%= product.categories.pluck(:name).join(', ') %>
        <br>
        <% if product.archived? %>
          <strong>Archived at:</strong>
          <%= product.updated_at %>
          <br>
        <% end %>
      </td>
      </td>
      <%= link_to 'Edit', edit_admin_product_path(product), class: "btn btn-secondary" %>
      <%= link_to 'Delete', admin_product_path(product), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </td>
    </tr>
  </table>
<% end %>

app/views/admin/products/index.xls.erb
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Description</th>
    <th>Archived</th>
    <th>On stock</th>
    <th>Created at</th>
    <th>Updated_at</th>
    <th>UUID</th>
    <th>Price</th>
  </tr>
  <% @products.each do |purchase| %>
    <tr>
      <th><%= purchase.id %></th>
      <th><%= purchase.name %></th>
      <th><%= purchase.description %></th>
      <th><%= purchase.archived %></th>
      <th><%= purchase.on_stock %></th>
      <th><%= purchase.created_at %></th>
      <th><%= purchase.updated_at %></th>
      <th><%= purchase.uuid %></th>
      <th><%= purchase.price %></th>
    </tr>
  <% end %>
</table>